# POST http://localhost:5000/admin/food
# Content-Type: application/json
# Accept: application/json

# {
#     "universe": "milky way"
# }

POST http://localhost:5000/order-details
Content-Type: application/json
Accept: application/json

{
    "userDetails": {
        "firstName": "Harry",
        "lastName": "Potter",
        "street": "17 Privet Drive",
        "city": "Little Whining",
        "postcode": "2345",
        "state": "NSW"
    },
    "foodOrder": {
        "Shrimp": 12,
        "Orange": 2
    }
}